language: java
jdk:
- oraclejdk8

# Using 'install' to run the clean to avoid Travis automatically calling
# `./gradlew assemble and duplicating my work
install:
    - ./gradlew clean

# Invoke our default tasks, whatever is defined as important in the
# build.gradle file
script:
    - ./gradlew

env:
  global:
  - secure: X71NKVXJjyG1C6/fZUTxdQ6HwAcaNRWSc0m/VRXsaiZwgXjIr+C+Uz9X4iu6Q52YAc+7CrvftAbIxgQhf+TBtvvnGeZgWXuYqf6Cx1weyL/6xsttOLsEGdtHU9jvrtw4tHRXxu/6F+8QAot8VRwUsCB4IL5Y3epshddbk+/1d9Q=

after_success: "./gradlew bintrayUpload -PbintrayUser=rtyler -PbintrayKey=${BINTRAY_KEY}"
