language: java
jdk:
- oraclejdk8

# Using 'install' to run the clean to avoid Travis automatically calling
# `./gradlew assemble and duplicating my work
install:
    - ./gradlew clean

# Invoke our default tasks, whatever is defined as important in the
# build.gradle file
script:
    - ./gradlew

env:
  global:
    secure: MzcJafov6+fztyym0hZFTxjirTAgVFqFRO4pSSoDUZV71jHBYRKLmQxiaYpqdl9d7Q7Jz7UfNZRSisNwZQdeZjs0B9yJwy9m1mDlJaUXIWN/xzW04qPnZ5zxh1yJHK+UHIw5G2qRZSE42m9G3TSRBlUz6OMk+tr2UYErfnKzcsc=

after_success:
    "./gradlew bintrayUpload -PbintrayUser=rtyler -PbintrayKey=${BINTRAY_KEY}"
